package com.tobzzo.mmmpk.ui.dashboardView.model

enum class DepartureStationEnum {
    BAZA_ZWIK,
    RACLAWICKA_PARK,
    SZPITALNA,
    PECKOWSKIEGO,
    PILSUDSKIEGO,
    SLOWACKIEGO,
    DYWIZJI_106_PIECHOTY_AK_1,
    DYWIZJI_106_PIECHOTY_AK_2,
    SIENKIEWICZA_PCPR,
    DWORZEC_PKP,
    SIENKIEWICZA_BP,
    STANISLAWY_DANECKIEJ,
    DYWIZJI_106_PIECHOTY_AK,
    TOPOLOWA,
    KAMIENNA,
    SZEWSKA_OS_PARKOWE,
    SZEWSKA,
    TRAUGUTTA_SZKOLA,
    KONOPNICKIEJ,
    RYNEK,
    SIENKIEWICZA_STARA_POLICJA
}